// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pattern_project.Database;

#nullable disable

namespace pattern_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421125314_InitAssetTpt")]
    partial class InitAssetTpt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pattern_project.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("OriginalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResponsiblePerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_OriginalValue_NonNegative", "[OriginalValue] >= 0");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("pattern_project.Models.CashAsset", b =>
                {
                    b.HasBaseType("pattern_project.Models.Asset");

                    b.ToTable("CashAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_OriginalValue_NonNegative", "[OriginalValue] >= 0");
                        });
                });

            modelBuilder.Entity("pattern_project.Models.CryptoAsset", b =>
                {
                    b.HasBaseType("pattern_project.Models.Asset");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.ToTable("CryptoAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_OriginalValue_NonNegative", "[OriginalValue] >= 0");

                            t.HasCheckConstraint("CK_CryptoAssets_Multiplier_NonNegative", "[Multiplier] >= 0");
                        });
                });

            modelBuilder.Entity("pattern_project.Models.CashAsset", b =>
                {
                    b.HasOne("pattern_project.Models.Asset", null)
                        .WithOne()
                        .HasForeignKey("pattern_project.Models.CashAsset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pattern_project.Models.CryptoAsset", b =>
                {
                    b.HasOne("pattern_project.Models.Asset", null)
                        .WithOne()
                        .HasForeignKey("pattern_project.Models.CryptoAsset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
