// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pattern_project.Database;

#nullable disable

namespace pattern_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422085552_AddMedicalRecordSoftDeleteAuditTrail")]
    partial class AddMedicalRecordSoftDeleteAuditTrail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pattern_project.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "Admin@123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "User@123",
                            Role = "User",
                            Username = "patientA"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "User@123",
                            Role = "User",
                            Username = "patientB"
                        });
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("ExaminationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDangerousInfectiousDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalVerificationCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecordCode")
                        .IsUnique();

                    b.HasIndex("PatientId", "ExaminationDate");

                    b.ToTable("MedicalRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicalRecords_VerificationCode_WhenInfectious", "([IsDangerousInfectiousDisease] = 0 AND [MedicalVerificationCode] IS NULL) OR ([IsDangerousInfectiousDisease] = 1 AND [MedicalVerificationCode] IS NOT NULL)");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.InpatientMedicalRecord", b =>
                {
                    b.HasBaseType("pattern_project.Domain.Entities.MedicalRecord");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("InpatientMedicalRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicalRecords_VerificationCode_WhenInfectious", "([IsDangerousInfectiousDisease] = 0 AND [MedicalVerificationCode] IS NULL) OR ([IsDangerousInfectiousDisease] = 1 AND [MedicalVerificationCode] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.OutpatientMedicalRecord", b =>
                {
                    b.HasBaseType("pattern_project.Domain.Entities.MedicalRecord");

                    b.Property<string>("EPrescriptionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("OutpatientMedicalRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicalRecords_VerificationCode_WhenInfectious", "([IsDangerousInfectiousDisease] = 0 AND [MedicalVerificationCode] IS NULL) OR ([IsDangerousInfectiousDisease] = 1 AND [MedicalVerificationCode] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("pattern_project.Domain.Entities.AppUser", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.InpatientMedicalRecord", b =>
                {
                    b.HasOne("pattern_project.Domain.Entities.MedicalRecord", null)
                        .WithOne()
                        .HasForeignKey("pattern_project.Domain.Entities.InpatientMedicalRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.OutpatientMedicalRecord", b =>
                {
                    b.HasOne("pattern_project.Domain.Entities.MedicalRecord", null)
                        .WithOne()
                        .HasForeignKey("pattern_project.Domain.Entities.OutpatientMedicalRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pattern_project.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
