// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pattern_project.Database;

#nullable disable

namespace pattern_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pattern_project.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Balance", "[Balance] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountNumber = "970400000001",
                            Balance = 500000000m,
                            CreatedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            AccountNumber = "970400000002",
                            Balance = 300000000m,
                            CreatedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("pattern_project.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "IsDeleted", "CreatedAt");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] > 0");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("pattern_project.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bank.local",
                            FullName = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "E86F78A8A3CAF0B60D8E74E5942AA6D86DC150CD3C03338AEF25B7D2D7E3ACC7",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@bank.local",
                            FullName = "Alice User",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "3E7C19576488862816F13B512CACF3E4BA97DD97243EA0BD6A2AD1642D86BA72",
                            Role = "User",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@bank.local",
                            FullName = "Bob User",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "3E7C19576488862816F13B512CACF3E4BA97DD97243EA0BD6A2AD1642D86BA72",
                            Role = "User",
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("pattern_project.Models.InterbankTransaction", b =>
                {
                    b.HasBaseType("pattern_project.Models.Transaction");

                    b.Property<string>("DestinationAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DestinationBankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DigitalSignature")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequiresDigitalSignature")
                        .HasColumnType("bit");

                    b.Property<long>("SourceAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("SwiftCode");

                    b.ToTable("InterbankTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_InterbankTransactions_DigitalSignature", "[RequiresDigitalSignature] = 0 OR [DigitalSignature] IS NOT NULL");

                            t.HasCheckConstraint("CK_InterbankTransactions_SwiftCode", "LEN([SwiftCode]) IN (8, 11)");
                        });
                });

            modelBuilder.Entity("pattern_project.Models.InternalTransaction", b =>
                {
                    b.HasBaseType("pattern_project.Models.Transaction");

                    b.Property<long>("DestinationAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceAccountId")
                        .HasColumnType("bigint");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("SourceAccountId");

                    b.ToTable("InternalTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_InternalTransactions_SourceDestination", "[SourceAccountId] <> [DestinationAccountId]");
                        });
                });

            modelBuilder.Entity("pattern_project.Models.Account", b =>
                {
                    b.HasOne("pattern_project.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("pattern_project.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("pattern_project.Models.Transaction", b =>
                {
                    b.HasOne("pattern_project.Models.User", "OwnerUser")
                        .WithMany("Transactions")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("pattern_project.Models.InterbankTransaction", b =>
                {
                    b.HasOne("pattern_project.Models.Transaction", null)
                        .WithOne()
                        .HasForeignKey("pattern_project.Models.InterbankTransaction", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pattern_project.Models.Account", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("pattern_project.Models.InternalTransaction", b =>
                {
                    b.HasOne("pattern_project.Models.Account", "DestinationAccount")
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pattern_project.Models.Transaction", null)
                        .WithOne()
                        .HasForeignKey("pattern_project.Models.InternalTransaction", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pattern_project.Models.Account", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationAccount");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("pattern_project.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
